### ISSUE TITLE
How do i build the release package for android?

### ISSUE THREAD

**Issue by lxjmaster** [beeware/beeware#110]
The commond `briefcase build android` just build a debug package.
How do i build the release package for android?

**Comment by freakboy3742** [comment]
`briefcase package` will produce the release APK.

The Briefcase docs contain a [HOWTO on packaging and releasing an app to the Play store](https://briefcase.readthedocs.io/en/latest/how-to/publishing/android.html).

**Comment by lxjmaster** [comment]
@freakboy3742 OK,Thank you very much!
