### ISSUE TITLE
briefcase build android failed with an exception

### ISSUE THREAD

**Issue by yunshangrourou** [beeware/beeware#113]
**build error log**
>>> 'D:\pfs\Java\jdk1.8.0_202\bin\javac' -version
[helloworld] Building Android APK...
>>> 'D:\codes\BeeWareProjects\beeware-tutorial\helloworld\android\gradle\Hello World\gradlew.bat' assembleDebug  

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'Hello World'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:3.5.3.
     Required by:
         project :
      > Could not resolve com.android.tools.build:gradle:3.5.3.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.5.3/gradle-3.5.3.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.5.3/gradle-3.5.3.pom'. Received status code 400 from server: Bad Request
      > Could not resolve com.android.tools.build:gradle:3.5.3.
         > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/gradle/3.5.3/gradle-3.5.3.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/android/tools/build/gradle/3.5.3/gradle-3.5.3.pom'. 
Received status code 400 from server: Bad Request

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

Error while building project.

**Comment by freakboy3742** [comment]
Thanks for the report. It looks like we've been bitten by the shutdown of JCenter; I've just pushed an update to the Briefcase template that should hopefully address this. You'll need to delete the `android` directory that briefcase created for your project and then re-run `briefcase create`. If that doesn't work for you, let us know and I'll re-open this ticket and investigate further.
