### ISSUE TITLE
Android app crash on launch

### ISSUE THREAD

**Issue by rcmz** [beeware/beeware#130]
The helloworld example runs fine on desktop linux but crashes on launch on android (emulator and physical device)
The android logcat seems to indicate that the error is caused by : 
``
11-04 15:53:44.183  7645  7645 E Python  :   File "/data/user/0/com.example.helloworld/files/python/user_code/app_packages/rubicon/java/api.py", line 45, in dispatch
11-04 15:53:44.183  7645  7645 E Python  :     val = getattr(pyinstance, method)(*args)
11-04 15:53:44.184  7645  7645 E Python  : AttributeError: 'TogaApp' object has no attribute 'onPrepareOptionsMenu'
``

**Comment by freakboy3742** [comment]
Oh bother... I merged a change to the Android template a day or two ago to support a new feature, and didn't test with the current *released* version of Toga.

I'll get a fix out as soon as possible. Apologies for the inconvenience.

**Comment by freakboy3742** [comment]
I've just released a new version of Toga that addresses this problem. Apologies again for the inconvenience.
