### ISSUE TITLE
More of a query than a bug report - use of httpx instead of requests in tutorial part 6

### ISSUE THREAD

**Issue by phlummox** [beeware/beeware#136]
**Describe the bug**

[Part 6][tute-6] of the tutorial suggests using the [httpx][httpx] library - I'm wondering why? Many Python developers by default probably reach for the [requests][requests] library when they need to interact with an HTTP API. So if the tutorial uses something else, it might be worth explaining the reasoning. (I suspect the answer is probably "better support for async fetching of resources", but haven't played with httpx to verify this.)

[tute-6]: https://github.com/beeware/beeware/blob/b6ce61cfd28233f8ef8c67423961f9067184f50f/docs/tutorial/tutorial-6.rst
[httpx]: https://www.python-httpx.org
[requests]: https://docs.python-requests.org/en/latest/

**To Reproduce**
1. Complete part 6 of tutorial, and note use of [httpx][httpx].

**Environment:**
 - n/a

**Comment by phlummox** [comment]
Oops, wrong project, sorry. I'll re-raise under 'toga'.

**Comment by phlummox** [comment]
... nope, looks like this is the right repo, after all: re-opening.

**Comment by freakboy3742** [comment]
Thanks for the suggestion, but the use of HTTPX was deliberate - and should become evident when you hit Tutorial 7. 

Requests doesn't have a built-in asynchronous mode, or an officially supported asynchronous extension/plugin. There are some async options out there, but in my experience they're nowhere near as well supported or integrated as requests itself.

On the other hand, HTTPX has been explicitly engineered from the outset for async compatibility - and it shows when you use the actual API in Tutorial 7.

**Comment by phlummox** [comment]
Hi, many thanks for the reply and your work on briefcase. My interest in briefcase arose from wanting to deploy several apps to Linux desktop, MacOS desktop and Android, but I've decided to pursue other options for doing so, and thus didn't end up completing Tutorial 7. I hope work on briefcase and the other Beeware tools goes well, cheers!
