### ISSUE TITLE
App gallery - real-world examples of apps built with Beeware

### ISSUE THREAD

**Issue by clstaudt** [beeware/beeware#137]
I just discovered Beeware - this might be just what I need to build a cross-platform desktop app.

I am working through the talks and tutorials. Also, the collection of feature demo examples is a great starting point. 

However, what I am still missing are some real-world examples of apps built with Beeware. Similar projects usually feature a gallery. Would it be possible to collect some to showcase what Beeware can really do?

(I've tried the iOs demo app, but it is currently crashing at startup)

**Comment by freakboy3742** [comment]
We have app galleries as part of the [Toga](https://toga.readthedocs.io/en/latest/background/success.html) and [Briefcase](https://briefcase.readthedocs.io/en/latest/background/success.html) project docs, on the basis that it's the individual tools that are being used.

We should possibly look at consolidating this somewhere as part of the main project website, but that would be something to address as part of a bigger IA review for the project; for now, I'm going to close this as wont fix.
