### ISSUE TITLE
Command to run an android emulator with an existing Android build.

### ISSUE THREAD

**Issue by Groupeffect** [beeware/beeware#140]
First of all I want't to thank the community for building such a great solution. I like the part where the android emulator comes into play. 
I just want to use the android emulator without installing Android Studio Desktop or other libraries ... simply because it is already delivered with Beeware. Does someone use the Beeware stack to run the emulator with different android builds that were not produced with briefcase necessarily?
I mean something like I take an android folder and copy paste it in to the project and type something like 

_Caution - not existing command example:_

`briefcase run android --foreign-build=./android --config=./.env`

`> opens an android phone emulator with a pre-build app from any repository you wish`

I think this would make the package extremely handy for testing purposes (at least for me). I like the idea to work most oft the time with python in venv.  
I would be thankful for any advise or solution. Maybe there is a very elegant solution which does not need additional libraries or installation.
I would also be very thankful if someone could give me an advise on which packages xor code lines are responsible for emulation ... perhaps it could lead to a merge request or just a code snippet for the community.

**Comment by freakboy3742** [comment]
@Groupeffect Thanks for the suggestion! This is an interesting idea, but it's probably out of scope for Briefcase itself. We don't want to give the perception that we're a "general purpose Android development tool"; we're very specifically targeting a Python user base.

The good news is that, for the most part, Briefcase is a wrapper around tools provided by other vendors (in this case, Google); the only difference is that we hide a lot of the annoying details needed to get started. Everything that Briefcase does *can* be done from the command line "natively", using vendor-provided tools.

In this case:
* Google provides the "Android SDK tools" as a standalone download, independent of the full Android Studio
* An emulator can be created with a tool called `avdmanager`
* The emulator can be started with `emulator`
* You can install an APK on a device using `adb install`
* You can start an APK with `adb shell am start`

Additional arguments are needed for each of these commands; if you run Briefcase with `-vv` it will output the full set of commands and flags required in the context of Briefcase operation. Or, you can dig into [the code for the Android SDK integration](https://github.com/beeware/briefcase/blob/master/src/briefcase/integrations/android_sdk.py) in Briefcase.
