### ISSUE TITLE
Is it possible to run the app from XCode project

### ISSUE THREAD

**Issue by CarlosNano** [beeware/beeware#148]
**Describe the bug**
I've been following the Tutorial 5 successfully ( https://docs.beeware.org/en/latest/tutorial/tutorial-5/index.html ). The app run fine if I run it with Briefcase.

Is it possible to run the App with XCode instead? If I open XCode and I run the app in a device, the app will crash in the line:
```
UIApplicationMain(argc, argv, nil, @"PythonAppDelegate");
```
With an error: `Thread 1: EXC_BAD_ACCESS (code=2, address=0x10302be08)`

**Screenshots**
![image](https://user-images.githubusercontent.com/72921935/164270301-e6f548f0-7449-4bc9-afca-9c4dd53a43c8.png)

**Environment:**
Operating System: 12.2.1
Python version: 3.7
 - Software versions:
   - Briefcase: 0.3.6
   - Toga: toga-cocoa>=0.3.0.dev3
   - ...

**Comment by freakboy3742** [comment]
Thanks for the report. I'm fairly certain you're hitting beeware/Python-Apple-support#131 - apps are currently running fine on the simulator, but they fail on physical devices. 

On that basis, I'm going to close this bug report; follow the above linked ticket for details. I'm hoping to be able to take a look  at the problem in the coming week or two.

**Comment by CarlosNano** [comment]
Thanks for pointing to that issue. I will keep an eye in the progress.

Unfortunately I'm also in a M1 so it won't make the simulator to work because of this: https://github.com/beeware/Python-Apple-support/issues/133

**Comment by freakboy3742** [comment]
You're getting this on the simulator as well? That's definitely not expected - I'm on an M1, and I haven't seen any problems running in the simulator. Can you confirm the exact version of Python, and the version of the Python support library that you're using (the latter should be mentioned in the log when you're creating the app)

**Comment by CarlosNano** [comment]
Just to clarify, the error log why I can't use the simulator is the following one:
```
ld: in /Users/myuser/dev/myProject/PythonHelloWorld/beeware-tutorial/beeware-venv/helloworld/iOS/Xcode/Hello World/Support/Python/libPython.a(pythonrun.o), building for iOS Simulator, but linking in object file built for iOS, for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Which I believe is the same problem than https://github.com/beeware/Python-Apple-support/issues/133

> Can you confirm the exact version of Python
```
python3 --version
Python 3.8.9
```
> Python support library that you're using
```
[helloworld] Installing support package...
Using support package https://briefcase-support.org/python?platform=iOS&version=3.8
... using most recent revision
Python-3.8-iOS-support.b7.tar.gz already downloaded
Unpacking support package...
```

**Comment by freakboy3742** [comment]
Ah - thanks for clarifying. It *is* possible to run in the simulator; however, you need to tweak the "VALID_ARCHS" setting to ensure you don't compile your app for ARM. This results in the simulated iOS app running in x86 emulation mode. That's still a bug - but there is a workaround.

**Comment by CarlosNano** [comment]
Nice, thanks for the tip.

Just to add more details ( in case anyone else who needed ).

With XCode 13 the parameter to use is `Excluded Architectures` it seems `VALID_ARCHS` was deprecated from XCode 12

With this settings, now seems to work:
![image](https://user-images.githubusercontent.com/72921935/165054862-ab822279-f0b1-456a-b26b-9ee036d7d7a3.png)

Thanks!
