### ISSUE TITLE
python -m pip install briefcase crashes with M1 and python 3.7.13

### ISSUE THREAD

**Issue by CarlosNano** [beeware/beeware#149]
**Describe the bug**
I'm trying to run the step in the tutorial `python -m pip install briefcase` 

I've installed `python 3.7.13` with `pyenv` 

After creating the virtual environment I've run: `python -m pip install briefcase`

This is the output: 
```
(beeware-venv) ➜  beeware-tutorial-python3-7 python -m pip install briefcase
Collecting briefcase
  Using cached briefcase-0.3.6-py2.py3-none-any.whl (86 kB)
Collecting dmgbuild>=1.3.3
  Using cached dmgbuild-1.5.2.tar.gz (38 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Yesterday I've run the same command with `python 3.8` and everything was working fine, unfortunately I've bumped into this other problem ( https://github.com/beeware/Python-Apple-support/issues/131 ), the problem seems not happening in 3.7 that's why I want to give it a try. 

**Expected behavior**
Installation of briefcase with no errors

**Screenshots**
![image](https://user-images.githubusercontent.com/72921935/164451499-fa064e0f-2dd3-4eb7-b2c9-585cbb5fa3d0.png)

Environment:
Operating System: 12.2.1
Python version: 3.7.13

**Comment by freakboy3742** [comment]
From the look of it, this is an issue with the version of pip and setup tools; having the older version of Python means the default version of setuptools is too old to work with pip itself. I'd suggest running `python -m pip install -U setuptools`, then retrying the install of `briefcase`. If that doesn't work, updating `pip` as well may work.

I'm not sure there's much else we can do to assist here; we already have setuptools and pip as dependencies, but we can't force those dependencies to be updated first.

**Comment by CarlosNano** [comment]
Nicely done!

Thanks

`python -m pip install -U setuptools` fixed the problem
