### ISSUE TITLE
Beeware tutorial breaks on linux

### ISSUE THREAD

**Issue by BrianHotopp** [beeware/beeware#151]
**Is your feature request related to a problem? Please describe.**
I'm on linux. When I went through the beware tutorial I got stuck for a bit because I didn't have the prerequisite system packages for toga (cairo, etc). This is mentioned in the toga tutorial but not in the beeware tutorial. I had to do some googling to find which packages I needed because there was no mention of this detail in the beeware tutorial.

**Describe the solution you'd like**
The beeware tutorial should "just work" ie if I'm following the instructions and using toga, it should mention that I need some system packages to complete the tutorial.

**Describe alternatives you've considered**
The beeware tutorial could potentially ignore the existence of other GUI toolkits and just push users to use toga. This way it would be more reasonable to put toga-specific instructions in the tutorial.

**Comment by freakboy3742** [comment]
The BeeWare tutorial *does* mention pre-requisites, in the [Install dependencies](https://docs.beeware.org/en/latest/tutorial/tutorial-0.html#install-dependencies) section. This includes (amongst many others) the Cairo dependency:
<img width="735" alt="Screen Shot 2022-04-23 at 8 18 23 am" src="https://user-images.githubusercontent.com/37345/164837615-2946a542-c8cf-4af6-bf26-c88482880c45.png">

**Comment by BrianHotopp** [comment]
I see it now! Thanks!
