### ISSUE TITLE
helloworld sample does not run on linux

### ISSUE THREAD

**Issue by PawelSpoon** [beeware/beeware#159]
**Describe the bug**
i have followed the steps on elementaryos based on ubuntu focal 
briefcase dev works, build creates an image but run returns

  File "/tmp/.mount_Hello_2X2Dh4/usr/app_packages/gi/overrides/__init__.py", line 32, in __getattr__
    return getattr(self._introspection_module, name)
  File "/tmp/.mount_Hello_2X2Dh4/usr/app_packages/gi/module.py", line 207, in __getattr__
    wrapper = metaclass(name, bases, dict_)
  File "/tmp/.mount_Hello_2X2Dh4/usr/app_packages/gi/types.py", line 247, in __init__
    register_interface_info(cls.__info__.get_g_type())
TypeError: must be an interface

types.py:
            if isinstance(cls.__info__, ObjectInfo):
                cls._setup_fields()
            elif isinstance(cls.__info__, InterfaceInfo):
                register_interface_info(cls.__info__.get_g_type())

**To Reproduce**
1. follow the stes
2. activate virtenv
3. briefcase create etc
4. briefcase dev
5. briefcase build
6. briefcase run
7. error in cosole
8. 
**Expected behavior**
see hello world app

**Screenshots**

**Environment:**
 - Operating System: elementaryos ubuntu 20.04
 - Python version: 3.8.10
 - Software versions:
   - Briefcase:0.3.7
   - Toga:
   - ...

**Additional context**

**Comment by freakboy3742** [comment]
Thanks for the report; this is a manifestation of beeware/briefcase#718; this particular manifestation should be addressed by beeware/briefcase#756.
