### ISSUE TITLE
how can do Android Message Push （Notification Listener Service）？

### ISSUE THREAD

**Issue by AGUIAtNight** [beeware/beeware#163]
**Is your feature request related to a problem? Please describe.**
I first use the beeware and toga ，in Android ，Android Message Push is important function ，but I do not learn in doc 

**Describe the solution you'd like**
May get a function or others course to help ，thanks you

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by freakboy3742** [comment]
We don't currently have any cross-platform support for push notifications. It is possible to use the native APIs through the bridging layer provided on Android; but unfortunately, we don't have any good documentation I can point you at for this.

**Comment by mhsmith** [comment]
Here's an example of calling the Android notification API from Python:

https://github.com/chaquo/chaquopy/blob/12.0.1/demo/app/src/main/python/chaquopy/demo/ui_demo.py#L81

With Toga, the `activity` in this example should be replaced with `self._impl.native`, where `self` is your `App` object.

Unfortunately, if your `targetSdkVersion` is 33 or higher, which is now the case with the default Briefcase template, you'll need to ask permission before showing a notification, and I don't have a Python example of that.

**Comment by jbesq-ml** [comment]
Does this ui demo provide access to Android's [https://developer.android.com/reference/android/telephony/SmsMessage](url) class? Can an app access text messages with Chaquopy, Toga, BeeWare etc?

**Comment by freakboy3742** [comment]
@jbesq-ml If you can write Java code to do something, you can write Python code to do the same thing. Use the [Chaquopy API](https://chaquo.com/chaquopy/doc/current/python.html) to import the API you want to invoke, and invoke it. You need to adhere to any requirements of the Java API you're invoking (such as requesting the relevant permissions), and there's a handful of cases that can be handled directly (subclassing abstract base classes with non-default constructors is the one notable case); but other than that, you can "just use" the API.

**Comment by jbesq-ml** [comment]
Perfect. Thank you.
