### ISSUE TITLE
Simplify onboarding process

### ISSUE THREAD

**Issue by freakboy3742** [beeware/beeware#17]
Our current dilemma: BeeWare has been (deliberately) structured as an umbrella project. As a result, there a whole bunch of different ways that people discover the project - some via beeware.org, some via a page on beeware.org, some via twitter, some via Github repositories.

The “umbrella” nature means that there are a bunch of smaller projects too - you don’t “Use beeware” or “install beeware” - you use Briefcase, or Toga, or VOC, or Batavia, and the pieces stack on top of each other to build a whole project.

But, this means that if you’re a first time arrival at the project, it can get confusing. And it gets confusing for us, too - someone says “I’m having a problem with the tutorial”, and we literally don’t know which tutorial they’re doing.

So - we need to work on our onboarding process.

The idea:

We make better use of the tutorial on this project (beeware). This project is a thin shim that installs other projects (like toga and briefcase), and provides a simplified interface to calling out to the other projects. That makes it an excellent starting point, so we turn the tutorial for beeware into the starting point for the whole project.

That entry point can also explain the bigger picture, like how the big pieces fit together, and can also funnel people into specific paths, and provide broad warnings - so, if people are interested in Django or Android as backends, they get a heads up that things are broken.

We can then funnel people from other projects to *this* tutorial, removing the project-specific tutorials for Toga, Briefcase etc - or, at least, to make “tutorial 0” of Toga, Briefcase etc a “go do the beeware tutorial", and make the tutorials for specific projects about how to drive deeper configuration of the tool.

The main website should also funnel people to this tutorial as part of the onboarding process.

Individual project READMEs should also be modified to direct people to the unified beeware tutorial.

**Comment by inhumantsar** [comment]
i feel like this breaks down into a few key parts:

* a quick explainer similar to [what's already going on the beeware.org site](https://beeware.org/project/using/cross-platform-mobile/) which covers the basics across the entire suite. 
* a centralized tutorial that everyone can run. it seems like the existing briefcase tutorial would be a good starting point for the tutorial side of this. lift and shift, adapt as necessary. 
* a broad status matrix for this beeware project, maybe also "known issues" sections in the project readmes. both should help prevent some users from writing github issues for existing problems.

thoughts?

**Comment by freakboy3742** [comment]
Agreed that this is a reasonable division of the work required.

As a stylistic thing, I'm not completely sold on the idea of a status matrix - A great big grid of information about platforms you don't use isn't really helpful if you're still getting to know a project. I'm also aware from the experience with the tutorial to date that the "one size fits all" tutorial doesn't really work - there are things you can say about how macOS works that have no contextual relevance if you're doing the Linux tutorial, or the iOS tutorial. Having a guided path that is (as close as is possible) customized to the learning path of a single user is likely to cause less problems.

I'd rather see something along the line of a "guided path" - something provides a general note that "some platforms have limitations/problems", and then feeds them into platform-specific tutorials, each of which is headlined with any appropriate warnings. That will also probably involve encouraging people to do a "desktop" tutorial before mobile or web - which is good for us generally, because the desktop platforms are more mature.

However, I'm also open to suggestions on how a "status matrix" approach, or a "single text" version could be made to work. 

Coordinating some of the changes so that we're not duplicating information will also be important. We will want to migrate information from the beeware.org site to the tutorial (or vice versa - whatever makes sense). This will require some consideration, but those three tasks should be able to be implemented independently.

**Comment by freakboy3742** [comment]
This has now been implemented. It needs to be added to the main BeeWare website as an entry point, but from the perspective of this project, the issue can be closed.
