### ISSUE TITLE
Issue in deploying app to Android

### ISSUE THREAD

**Issue by ujur007** [beeware/beeware#178]
### Describe the bug

I have followed the Beeware tutorial to deploy the basic application to Android device. The problem which I got is regarding finding the source.properties file. 

> com.android.builder.errors.EvalIssueException: NDK at /user/.cache/briefcase/tools/android_sdk/ndk/21.4.7075529 did not have a source.properties file

Does anyone knows how to solve this error?

### Expected behavior

Wanted to run the app on android device.!

### Environment

- Operating System: Linux mint 64-bits
- Python version: 3.8.10
- Software versions: 
  - Briefcase:latest 
  - Toga:latest
  - ...

### Logs

```

```

**Comment by mhsmith** [comment]
This is probably caused by the NDK installation being interrupted during a previous build. Try deleting the directory briefcase/tools/android_sdk/ndk/21.4.7075529, and it should be automatically reinstalled the next time you run an Android Briefcase command.

**Comment by ujur007** [comment]
Thanks, seems that was the issue.
