### ISSUE TITLE
Need Help Figuring Out What I'm Not Understanding

### ISSUE THREAD

**Issue by ubuntume** [beeware/beeware#18]
If I run the application I have made using the command python -m application name it runs and does get a window, but I i use the beeware run appname route or the briefcase python setup.py linux -s route I get this error that is associated with podium. However, I built podium from scratch and verified it working but when I use either method it simply opens a window showing the files in a file manager window without actually starting the code I wrote. Below is the error I keep getting if I don't install podium.

```
(venv) cchatmon@Amethyst:~/Desktop/beeware/claron$ beeware run linux
Running Briefcase...
>>> python setup.py linux -s

running linux

 * Updating user code...
 * Installing requirements...
No requirements.
 * Installing platform requirements...
Collecting toga-gtk==0.3.0.dev11
  Using cached https://files.pythonhosted.org/packages/58/03/fd1b50d3e694191119e828e1455309e265cb80a17ea3a1f39eb0b411dc26/toga_gtk-0.3.0.dev11-py3-none-any.whl
Collecting toga-core==0.3.0.dev11 (from toga-gtk==0.3.0.dev11)
  Using cached https://files.pythonhosted.org/packages/e0/d2/725f505441428638d97cde2eea794a6a328deeec58bfd615fd3a71baa8ad/toga_core-0.3.0.dev11-py3-none-any.whl
Collecting pycairo>=1.17.0 (from toga-gtk==0.3.0.dev11)
Collecting pygobject>=3.14.0 (from toga-gtk==0.3.0.dev11)
Collecting gbulb>=0.5.3 (from toga-gtk==0.3.0.dev11)
Collecting travertino>=0.1.0 (from toga-core==0.3.0.dev11->toga-gtk==0.3.0.dev11)
  Using cached https://files.pythonhosted.org/packages/56/3f/f03efe63c2bdc72763ac39777c9ebbab98605ced5c74aefe48b4fa0abb4d/travertino-0.1.2-py3-none-any.whl
ERROR: toga 0.3.0.dev13 has requirement toga-gtk==0.3.0.dev13; sys_platform == "linux", but you'll have toga-gtk 0.3.0.dev11 which is incompatible.
Installing collected packages: travertino, toga-core, pycairo, pygobject, gbulb, toga-gtk
Successfully installed gbulb-0.6.1 pycairo-1.18.1 pygobject-3.32.2 toga-core-0.3.0.dev11 toga-gtk-0.3.0.dev11 travertino-0.1.2
 * Installing project code...
Processing /home/cchatmon/Desktop/beeware/claron
Building wheels for collected packages: claron
  Building wheel for claron (setup.py) ... done
  Created wheel for claron: filename=claron-0.0.1-cp35-none-any.whl size=3142 sha256=5a9e38b3c2540be368f2116a278ad0c6cb667892fe020e7633268b622e50208d
  Stored in directory: /tmp/pip-ephem-wheel-cache-5goo0afd/wheels/9b/38/a6/5baa2cd9a8662afc2548a73864c21c40936a22c2ecc9da4dfb
Successfully built claron
Installing collected packages: claron
Successfully installed claron-0.0.1
 * No icons defined - using default...
 * No splash screen defined...

Installation complete.
Starting Claron
/home/cchatmon/Desktop/beeware/venv/bin/python3: No module named podium

App started.
```

**Comment by freakboy3742** [comment]
Looks like an error on my part - I pushed an update to the Linux application template over the weekend, and inadvertently hard-coded the name of the app (podium) rather than using the template name. 

If you delete the linux directory created beeware and re-run `beeware linux run`, you should have more success.

Apologies for the confusion

**Comment by ubuntume** [comment]
Thanks so much. I feel so. I feel bad now. I gave up on linux and started
farting off on windows - the playstation of OS. Nothing productive just
games lol. Can i ask you - how can I learn to help and know about this
project. Im thinking about college, but really want to know where to really
dig into computer science and understanding what beeware builders
understand and where they're going.

**Comment by freakboy3742** [comment]
@ubuntume If you want to get involved with the project, we have a [contribution guide](https://beeware.org/contributing/how/first-time/); that can give you some places to start looking. My overall advice, though - have a goal in mind. Not just "I want to learn to program"; *why* do you want to learn? What problem do you want to solve? What do you want to build? Having a goal like that will help you narrow down what you focus on. BeeWare is a huge collection of projects, and it's only a small part of open source as a whole; knowing what you want to do will help determine what you need to learn, and, in turn, where you will be able to contribute.
