### ISSUE TITLE
Add Trusted Publishers to all Beeware projects that are published to PyPI

### ISSUE THREAD

**Issue by sethmlarson** [beeware/beeware#219]
### What is the problem or limitation you are having?

Solving a problem for @freakboy3742, instead of needing to manage authentication credentials per repository these projects can use a [Trusted Publisher](https://blog.pypi.org/posts/2023-04-20-introducing-trusted-publishers/) in order to publish to PyPI using GitHub OIDC.

I've opened the issue here for lack of a better "meta" issue location, happy to move this elsewhere if that makes sense.

### Describe the solution you'd like

This issue can be completed in two steps:

- Create PRs to all projects publishing to PyPI to augment the deployment pipeline to use the new Trusted Publishers feature.
- Optionally configure the trusted publishers individually per project on PyPI. This would require admin access to the projects on PyPI while the work is being done but can be revoked after completion of the work. Perhaps admin access can be configured via the Beeware Organization, but I am not sure.

### Describe alternatives you've considered

It's okay to leave the deployment pipelines as-is, however this would require continuing to maintain long-lived credentials capable of publishing to any Beeware (or @freakboy3742 owned) project on PyPI.

### PyPI projects which have been completed

- [x] briefcase (https://github.com/beeware/briefcase/pull/1233)
- [x] toga (shared repos, https://github.com/beeware/toga/pull/1900)
  - [x] toga-ios
  - [x] toga-dummy
  - [x] toga-gtk
  - [x] toga-cocoa
  - [x] toga-winforms
  - [x] toga-android
  - [x] toga-web
  - [x] toga-demo
  - [x] toga-core
- [x] rubicon-objc (https://github.com/beeware/rubicon-objc/pull/301)
- [x] travertino (https://github.com/beeware/travertino/pull/55)
- [x] gbulb (https://github.com/beeware/gbulb/pull/80)
- [x] ~std-nslog~ (not applicable, doesn't have a release pipeline)

**Comment by freakboy3742** [comment]
For transparency - I've given @sethmlarson access to BeeWare's PyPI config so he can modify the configurations to support moving to trusted publishers.

**Comment by sethmlarson** [comment]
@freakboy3742 Okay, I've completed the work for all the projects that have existing publishing workflows in GitHub Actions. All the pull requests are linked in this issue.

`std-nslog` is different because it seems to only be using git tags instead of GitHub Releases, if you'd like me to do the same work as others I'd like to confirm whether you want to release on git tags or releases as is done for other projects. Let me know!

I've double checked every project on the list that has been completed that it is configured correctly. If you don't require any further configuration of trusted publishers in PyPI I can have my membership to the organization removed.

**Comment by freakboy3742** [comment]
Cleaning up; I've removed @sethmlarson from BeeWare's PyPI org.

**Comment by freakboy3742** [comment]
@sethmlarson I've pushed updates to the 5 PRs adding the analogous configurations for Test PyPI, and I've updated the configuration on Test PyPI to have the analogous trusted configurations for the "release.yml" workflows. Could I ask for a quick check that I've done the right thing here (and that Test PyPI actually supports this configuration?)

**Comment by freakboy3742** [comment]
@sethmlarson No worries about the delay - totally understood. And yes - the testPyPI trusted publisher configs all use `release.yml`, not `publish.yml`, so it's not a raw copy-and-paste.

**Comment by freakboy3742** [comment]
I've now merged all the individual project PRs, so I'll close this issue.
