### ISSUE TITLE
Project links in documentation are broken

### ISSUE THREAD

**Issue by adamtheturtle** [beeware/beeware#22]
👋 

When I visit https://beeware.readthedocs.io/en/latest/, I see links to various tools near the top of the page.

However, they all go to the ReadTheDocs page not found page.

For example, the Briefcase link is to https://beeware.readthedocs.io/en/latest/briefcase.readthedocs.org.

I suspect that this is because the protocol was not specified in the link and therefore Sphinx treats it as a relative link.

**Comment by adamtheturtle** [comment]
(Perhaps useful: I have found `intersphinx` to be great for managing these kinds of links)

**Comment by freakboy3742** [comment]
Thanks for the report! I'll make a note to take a look at intersphinx, too - might be a little bit of overkill for this particular usage, but looks like it could be really useful in other places.
