### ISSUE TITLE
Docs/Tutorial: `pip install briefcase` crashes in Windows, add info box to explain

### ISSUE THREAD

**Issue by NMertsch** [beeware/beeware#236]
### What is the problem or limitation you are having?

The [tutorial](https://docs.beeware.org/en/latest/tutorial/tutorial-1.html#install-the-beeware-tools) says `python -m pip install briefcase`, which runs fine.

Users (like me) might still use `pip install briefcase` out of habit.

Since briefcase requires a fairly recent version of setuptools (see [pyproject.toml](https://github.com/beeware/briefcase/blob/43fd921ca093acc769f600601d5c14a0fa5817ce/pyproject.toml#L2C12-L2C12)), installing briefcase might upgrade `setuptools` and thus `pip`.

This can lead to the following sequence:
1. Successfully uninstalled setuptools-56.0.0
2. Successfully uninstalled pip-21.1.1
3. ERROR: Could not install packages due to an OSError [...]

### Describe the solution you'd like

Using `python -m pip` instead of `pip` works fine. I propose to add an info box so that users like me are not surprised by this error and know what to do.

### Describe alternatives you've considered

Since the tutorial advertises the correct command, you could say "if you don't follow the tutorial, that's on you". I still think that documenting it is good, since using `pip` instead of `python -m pip` is a common pattern.

**Comment by freakboy3742** [comment]
Agreed - anything we can do to keep people on the right track in the early stages of the tutorial is a good idea. 

It may also be useful to provide a link to some background information on the topic - [Brett Cannon's blog post](https://snarky.ca/why-you-should-use-python-m-pip/) is a really good source for this.
