### ISSUE TITLE
Does the generated apk support Android 7?

### ISSUE THREAD

**Issue by ycw01** [beeware/beeware#267]
### What is the problem or limitation you are having?

>briefcase create android

*************************************************************************
** WARNING: JAVA_HOME does not point to a Java 17 JDK                  **
*************************************************************************

    Android requires a Java 17 JDK, but the location pointed to by the
    JAVA_HOME environment variable:

    C:\Program Files\Java\jdk1.8.0_121

    isn't a Java 17 JDK (it appears to be Java 1.8.0_121).

    Briefcase will use its own JDK instance.

*************************************************************************

### Describe the solution you'd like

I don’t know where I can set the Android SDK version and jdk version. The apk generated by the default jdk17 and Android 30 cannot run normally on Android 7.

### Describe alternatives you've considered

I hope that the Android version and jdk version can be customized to support lower versions of Android.

**Comment by mhsmith** [comment]
This message doesn't have anything to do with the Android version, but it's only a warning, so it should be harmless.

Briefcase's minimum supported Android version is indeed Android 7 (API level 24). If you're having a problem running your app on that version, please post your log.

**Comment by ycw01** [comment]
> This message doesn't have anything to do with the Android version, but it's only a warning, so it should be harmless.
> 
> Briefcase's minimum supported Android version is indeed Android 7 (API level 24). If you're having a problem running your app on that version, please post your log.

09-29 16:18:39.621  2825  2825 D MainActivity: Running main module helloworld
09-29 16:18:39.921  2825  2825 D AndroidRuntime: Shutting down VM
09-29 16:18:39.925  2825  2825 E AndroidRuntime: FATAL EXCEPTION: main
09-29 16:18:39.925  2825  2825 E AndroidRuntime: Process: com.example.helloworld, PID: 2825
09-29 16:18:39.925  2825  2825 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.helloworld/org.beeware.android.MainActivity}: com.chaquo.python.PyException: java.lang.NoClassDefFoundError: android.graphics.text.LineBreaker
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2958)
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3093)
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1823)
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6825)
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
09-29 16:18:39.925  2825  2825 E AndroidRuntime: Caused by: com.chaquo.python.PyException: java.lang.NoClassDefFoundError: android.graphics.text.LineBreaker
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        at com.chaquo.python.PyObject.callAttr(PyObject.java:225)
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        at org.beeware.android.MainActivity.onCreate(MainActivity.java:85)
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7144)
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7135)
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2938)
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        ... 11 more
09-29 16:18:39.925  2825  2825 E AndroidRuntime: Caused by: java.lang.NoClassDefFoundError: android.graphics.text.LineBreaker
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        at java.lang.Class.classForName(Native Method)
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        at java.lang.Class.forName(Class.java:453)
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        at <python>.java.chaquopy.CQPEnv.FindClass(env.pxi:63)
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        at <python>.java.chaquopy.JavaClass.__new__(class.pxi:79)
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        at <python>.java.chaquopy.new_class(class.pxi:67)
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        at <python>.java.chaquopy.jclass(class.pxi:59)
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        at <python>.java.chaquopy.jclass(class.pxi:53)
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        at <python>.java.chaquopy.jclass(class.pxi:34)
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        at <python>.toga_android.libs.android.graphics.<module>(graphics.py:17)
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        at <python>.java.chaquopy.import_override(import.pxi:26)
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        at <python>.toga_android.app.<module>(app.py:9)
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        at <python>.java.chaquopy.import_override(import.pxi:26)
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        at <python>.toga_android.factory.<module>(factory.py:2)
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        at <python>.importlib._bootstrap._call_with_frames_removed(<frozen importlib._bootstrap>:228)
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        at <python>.importlib._bootstrap_external.exec_module(<frozen importlib._bootstrap_external>:850)
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        at <python>.java.android.importer.exec_module(importer.py:554)
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        at <python>.java.android.importer.exec_module(importer.py:606)
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        at <python>.importlib._bootstrap._load_unlocked(<frozen importlib._bootstrap>:680)
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:986)
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:1007)
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        at <python>.importlib._bootstrap._gcd_import(<frozen importlib._bootstrap>:1030)
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        at <python>.importlib.import_module(__init__.py:127)
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        at <python>.toga.platform.get_platform_factory(platform.py:122)
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        at <python>.toga.app.__init__(app.py:323)
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        at <python>.helloworld.app.main(app.py:43)
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        at <python>.__main__.<module>(__main__.py:4)
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        at <python>.runpy._run_code(runpy.py:87)
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        at <python>.runpy._run_module_code(runpy.py:97)
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        at <python>.runpy.run_module(runpy.py:225)
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        at <python>.chaquopy_java.call(chaquopy_java.pyx:354)
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrowsNative(chaquopy_java.pyx:326)
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        at com.chaquo.python.PyObject.callAttr(PyObject.java:221)
09-29 16:18:39.925  2825  2825 E AndroidRuntime:        ... 16 more
09-29 16:18:39.933  1580  1846 W ActivityManager:   Force finishing activity com.example.helloworld/org.beeware.android.MainActivity
09-29 16:18:39.938  2825  2825 W System.err: java.lang.Exception: call killProcess callstack! pid=2825
09-29 16:18:39.938  2825  2825 W System.err:    at android.os.Process.killProcess(Process.java:915)
09-29 16:18:39.938  2825  2825 W System.err:    at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:157)
09-29 16:18:39.938  2825  2825 W System.err:    at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
09-29 16:18:39.938  2825  2825 W System.err:    at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
09-29 16:18:39.938  2825  2825 W System.err:    at java.lang.Thread.dispatchUncaughtException(Thread.java:1955)
09-29 16:18:39.938  2825  2825 I Process : Sending signal. PID: 2825 SIG: 9

**Comment by ycw01** [comment]
I have tested Android 7, 8, and 9, and all of them report this error when the app is launched

**Comment by mhsmith** [comment]
See https://github.com/beeware/toga/issues/2032#issuecomment-1637052439.

**Comment by ycw01** [comment]
> 请参阅[beeware/toga#2032（评论）。](https://github.com/beeware/toga/issues/2032#issuecomment-1637052439)



> 请参阅[beeware/toga#2032（评论）。](https://github.com/beeware/toga/issues/2032#issuecomment-1637052439)



> See [beeware/toga#2032 (comment)](https://github.com/beeware/toga/issues/2032#issuecomment-1637052439).

[tool.briefcase.app.helloworld.android]
#requires = [
#    "toga-android~=0.3.1"
#]
requires = [
    "git+https://github.com/beeware/toga#subdirectory=core",
    "git+https://github.com/beeware/toga#subdirectory=android",
]
Is this the correct configuration?

**Comment by ycw01** [comment]
> See [beeware/toga#2032 (comment)](https://github.com/beeware/toga/issues/2032#issuecomment-1637052439).

```
[tool.briefcase.app.helloworld.android]
#requires = [
#    "toga-android~=0.3.1"
#]
requires = [
    "git+https://github.com/beeware/toga#subdirectory=core",
    "git+https://github.com/beeware/toga#subdirectory=android",
]
```
Is this the correct configuration?

**Comment by mhsmith** [comment]
Yes.

**Comment by ycw01** [comment]
> Yes.

Thank you. Beeware is popular in mainland China, and it would be great to have Simplified Chinese documentation for Beeware-related projects.

**Comment by freakboy3742** [comment]
@ycw01 We'd love to have documentation for languages other than English - however, we don't speak languages other than English. If someone wants to contribute translations to our docs, we'd be happy to incorporate it.
