### ISSUE TITLE
How to get the Permission to write file on Android platform?

### ISSUE THREAD

**Issue by lihuaming07** [beeware/beeware#292]
### What is the problem or limitation you are having?

I would like to save some data for my app, however, I found it hard to make it becase of PermissionError.How can I apply for Permission to write file and read file?
![image](https://github.com/beeware/beeware/assets/71958128/4c07196e-9209-4b81-9798-571e71d8b8b8)

### Describe the solution you'd like

I would like to know that whether there is an api to get the file permission?

### Describe alternatives you've considered

Like other Android apps, get the permission of writting file by applying, and then send a diolog so that user can accept my app to write file to save application data.

### Additional context

This is my code, but it couldn't work expectedly due to PermissionError.
![image](https://github.com/beeware/beeware/assets/71958128/f7c09a46-a342-470a-9a36-423c554db2f3)

**Comment by lihuaming07** [comment]
I solve this problem by another way.I now knew that app can only write the file at the dictionary _**/android/data/package_name**_

**Comment by lihuaming07** [comment]
But I still expect that I could get the permission to write file at the root path.

**Comment by rmartin16** [comment]
Android has a more complex file system interaction API than common Desktop OSes. Therefore, it may not be possible to interact with arbitrary parts of the file system without the necessary permissions or APIs.

Some of the linked Issues and PRs below discuss this and work to implement it:
- https://github.com/beeware/toga/issues/1171
- https://github.com/beeware/toga/pull/1158
- https://github.com/beeware/briefcase/pull/1599

Right now, Toga (and the rest of the BeeWare suite) do not support full Android file system access out of the box. But work is being done to support this. As in some of the links above, custom implementations are possible to achieve these goals.

I'm closing this Issue given the existing documentation. Feel free to log additional Issues or ask any questions as Discussions or in the [Discord](https://beeware.org/bee/chat/).
