### ISSUE TITLE
Ubuntu 24.04 (noble) is not providing `gir1.2-webkit2-4.0`

### ISSUE THREAD

**Issue by rmartin16** [beeware/beeware#333]
### Describe the bug

For Ubuntu users, the pre-reqs say to install `gir1.2-webkit2-4.0` but Ubuntu 24.04 is only providing `gir1.2-webkit2-4.1`.

https://packages.ubuntu.com/lunar/gir1.2-webkit2-4.0
https://packages.ubuntu.com/lunar/gir1.2-webkit2-4.1

### Steps to reproduce

```console
user@vm-ubuntu24:~$ sudo apt update && sudo apt install build-essential git pkg-config python3-dev python3-venv libgirepository1.0-dev libcairo2-dev gir1.2-webkit2-4.0 libcanberra-gtk3-module
[sudo] password for user: 
Hit:1 http://security.ubuntu.com/ubuntu noble-security InRelease
Hit:2 http://gb.archive.ubuntu.com/ubuntu noble InRelease   
Hit:3 http://gb.archive.ubuntu.com/ubuntu noble-updates InRelease
Hit:4 http://gb.archive.ubuntu.com/ubuntu noble-backports InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
14 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package gir1.2-webkit2-4.0 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
```

### Expected behavior

Installing pre-reqs works for all supported platforms.

We can't just say to install `gir1.2-webkit2-4.1` instead because 20.04 (focal) only provides `gir1.2-webkit2-4.0`....unless we drop 20.04, I suppose...but that seems pre-mature.

The directions can be further delineated for Ubuntu versions.....or we could craft an install command that takes version in to account..

### Environment

- Operating System: Ubuntu 22.04 noble beta
- Python version: 3.12.3
- Software versions:
  - Briefcase: `0.3.17`
  - Toga: `0.4.2`

### Additional context

This will also affect targeting Ubuntu 24.04 with Briefcase...but wanted to get this out there since Ubuntu 24.04 drops in a few days and the tutorial session is in a few weeks.

All the Toga documentation should be updated as well.

**Comment by mhsmith** [comment]
Is there another package we could instruct people to install instead, which has the same name on both versions of Ubuntu, and depends on the appropriate `gir1.2-webkit2-X.Y` package?

**Comment by rmartin16** [comment]
> Is there another package we could instruct people to install instead, which has the same name on both versions of Ubuntu, and depends on the appropriate `gir1.2-webkit2-X.Y` package?

### Ubuntu
Not that I see.
```console
> apt rdepends gir1.2-webkit2-4.1
gir1.2-webkit2-4.1
Reverse Depends:
  Depends: gir1.2-devhelp-3.0 (>= 2.26)
  Depends: thawab
  Depends: lutris
  Depends: ubuntu-budgie-desktop-minimal
  Depends: ubuntu-budgie-desktop
  Depends: typecatcher
  Depends: sugar-browse-activity
  Depends: ruby-webkit2-gtk
  Depends: revolt
  Depends: rednotebook
  Depends: python3-webview
  Recommends: python3-sugar3
 |Depends: python3-keyman-config
  Depends: python3-jarabe
  Depends: minigalaxy
  Depends: libwebkit2gtk-4.1-dev (= 2.44.0-2)
  Depends: libgtk3-webkit2-perl
  Depends: gufw
  Depends: gp-saml-gui
  Depends: gnome-sushi
  Depends: gir1.2-gepub-0.7
  Depends: ubiquity-frontend-gtk
  Depends: formiko
  Depends: font-downloader
 |Suggests: exaile
  Depends: cyclograph-gtk3
  Depends: apturl
  Depends: apostrophe
  Depends: ubuntu-release-upgrader-gtk
```

Also, this is already a problem for Linux Mint 22. To that end, this may be a problem for other platforms as well.

### RHEL
If we consider RHEL, we're currently using `webkit2gtk3`....but for Fedora this package was [removed/obsoleted](https://src.fedoraproject.org/rpms/webkit2gtk3) and somewhere must be listed as an alias for `libwebkit2gtk4.0`. This feels more like an artifact of history rather than "use `webkit2gtk3` as a moving pointer for the latest `libwebkit2gtkX.Y`". And if I consider Almalinux, `webkit2gtk3` points to an older version and they don't appear to even offer a package with API 4.1 for webkit2.

### OpenSUSE
OpenSUSE Tumbleweed is using `libwebkit2gtk3`. I cannot find where this alias is defined but it's currently installing `libwebkit2gtk-4_0-37`. It is not clear if or when this might switch over to the `libwebkit2gtk-4_1-0` package.

### Arch
On Arch, we're using `webkit2gtk` which installs `libwebkit2gtk-4.0`. However, a package named `webkit2gtk-4.1` exists to provide `libwebkit2gtk-4.1`. Here, as with Tumbleweed, it's unclear if `webkit2gtk` will change what it installs in the future.

### Conclusion
Since Arch and OpenSUSE are both rolling releases, it may make more sense to directly use the version 4.1 package if only to offer better predictability and transparency of what's actually being used.

For RHEL, probably best leaving as is until the situation becomes clearer for the `webkit2gtk3` package alias.

For Debian, for our purposes here anyway....we could consider a bit of a hack...
```
sudo apt install gir1.2-webkit2-4.*
```
This'll just install all available versions.

**Comment by freakboy3742** [comment]
Actually, the easier solution might be to just remove the webkit solution altogether. The BeeWare tutorial doesn't use any web widgets; so we should be able to safely remove those dependencies from the tutorial install list.

We *do* need to modify the README for toga-gtk, though (or rework the dependency descriptions to highlight that the webkit libraries are only needed if you're using toga.WebView). The Briefcase bootstraps likely needs some additional notes/sections to accomodate this change.

**Comment by rmartin16** [comment]
> Actually, the easier solution might be to just remove the webkit solution altogether. The BeeWare tutorial doesn't use any web widgets; so we should be able to safely remove those dependencies from the tutorial install list.

That's true; although, I often use the prerequisites page in the tutorial as the de facto source of truth for people missing packages. So, removing this prereq entirely will complicate that story a bit...

**Comment by freakboy3742** [comment]
True - but to mitigate that, I would suggest modifying the error message raised at runtime to include an explicit link to documentation that then includes explicit package installation instructions (presumably by breaking the [current notes](https://toga.readthedocs.io/en/stable/reference/api/widgets/webview.html#notes) into a clearly defined "system requirements" block, doing the same with MapView). That way, there will be an explicit path to the explicit instructions to fix that problem when a user gets a failure when attempting to use WebView.
