### ISSUE TITLE
MarkupSafe dependency

### ISSUE THREAD

**Issue by roipoussiere** [beeware/beeware#56]
Following the [beeware tutorial](https://docs.beeware.org/en/latest/tutorial/tutorial-3.html), I installed beeware on ubuntu-16.04 Docker image, in order to build an AppImage:

```
$ apt-get update
$ apt-get install git python3-dev python3-pip libgirepository1.0-dev libcairo2-dev libpango1.0-dev libwebkitgtk-3.0-0 gir1.2-webkit-3.0
$ python3 -m pip install --pre beeware
```

However this was not sufficient and I had to install the `MarkupSafe` Python package:

```
python3 -m pip install MarkupSafe
```

It could be practical to add the `MarkupSafe` package as a dependency in order automatically install it with `pip install beeware`.

**Comment by freakboy3742** [comment]
Ok - we don't directly depend on Jinja, either; I'm guessing cookiecutter is the source of the problem here. Can you share your `pip freeze` list from a clean virtual environment that has nothing but `briefcase` installed in it?

**Comment by freakboy3742** [comment]
What's *really* weird is that MarkupSafe is [listed as a dependency for Jinja2](https://github.com/pallets/jinja/blob/2.11.x/setup.py#L53)...

**Comment by freakboy3742** [comment]
Without any more specific information, I'm going to close this. I can't see any chain of dependencies that would lead to having briefcase installed, and Jinja installed, but *not* getting MarkupSafe installed. MarkupSafe has been a requirement for at least 4 years in Jinja, so unless the install actually failed somehow, or there's a *very* old version of Jinja in the environment, I can't work out how you'd reproduce this behavior.

If you are able to provide a set instructions for reproducing this failure, I'm happy to reopen (and fix) the ticket.
