### ISSUE TITLE
okay I dont know why the emulator is not working does anybody know how to solve it?

### ISSUE THREAD

**Issue by adityasaxena-crypto** [beeware/beeware#73]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment:**
 - Operating System:
 - Python version:
 - Software versions:
   - Briefcase:
   - Toga:
   - ...

**Additional context**

**Comment by freakboy3742** [comment]
I'm going to close this - the original report doesn't provide any details about the problem you're having, errors you're seeing, the platform you're using, or anything else that would help us diagnose the issue.
