### ISSUE TITLE
Update Text In Tutorial

### ISSUE THREAD

**Issue by kaijuking** [beeware/beeware#79]
**Describe the bug**
There are two places where the tutorial text should be updated to fix either a spelling error or to provide better clarity.

**To Reproduce**
Text Issue 1
1. GIVEN the user is following the Beeware Android tutorial
2. AND the user navigates to the "Tutorial 5 - Taking it Mobile" page
3. WHEN the user scrolls down to the text right above the "Next Steps" section
4. THEN the text "In future" should be displayed as "In the future"

Text Issue 2
1. GIVEN the user is following the Beeware tutorial
2. AND the user navigates to the "Tutorial 7 - Publishing your app" page
3. AND the user is reading the text in the "Next steps" section
4. THEN the word "taster" should be displayed as "taste"

**Expected behavior**
Text Issue 1 - Suggest updating the text "In future" to "In the future"
Text Issue 2 - Suggest updating the text "taster" to "taste"

**Screenshots**
Text Issue 1
![test_issue_1](https://user-images.githubusercontent.com/17255794/93010872-d39c3600-f545-11ea-857f-3bca6836a245.PNG)

Text Issue 2
![test_issue_2](https://user-images.githubusercontent.com/17255794/93010874-d4cd6300-f545-11ea-9119-50437c6de7bc.PNG)

**Environment:**
 - Chrome Version 85.0.4183.102 (Official Build) (64-bit)

**Additional context**
- NA

**Comment by freakboy3742** [comment]
Thanks for the bug report; would you be able to turn this into a PR?

**Comment by kaijuking** [comment]
Sure! Would I just clone the repo locally and make the changes on master?

**Comment by kaijuking** [comment]
I cloned the repo locally and created a new branch off of master. After making the changes to the new branch I attempted to push the changes (commit was signed) but got a 403 error message. Would you be able to help me understand what steps I'm missing? Thank you very much!

**Comment by freakboy3742** [comment]
Did you fork the repository first? If you've cloned the "upstream" repository (i.e, beeware/beeware), you won't be able to push a branch to that repository, because you're not a member of the organisation (which would then cause a 403 permission error). If you fork the repository into your own account, you can push a branch to *that* fork, and then submit a PR from that branch.

**Comment by kaijuking** [comment]
Thank you very much for the help @freakboy3742 ! Much appreciated. Once I read your message I realized my initial mistake in attempting to update the original branch which I do not have access to. Hence the 403 makes perfect sense. I just created and submitted a pull request. Please let me know if I have forgotten anything and/or if there are any questions. Thank you!
