### ISSUE TITLE
window tesseract on android

### ISSUE THREAD

**Issue by rustagiadi95** [beeware/beeware#82]
I am trying to create an application on android but holding the window native tesseract OCR.
Naturally, the app runs fine in dev mode....but fails in running mode...since the independent application although having pytesseract does not have the tesseract binary.

So is there any way to help pytesseract use the tesseract binary in run mode?

Also, I want to know how to put briefcase in debug mode....(for me to see the exact issue why the app is not running in run mode)

for example it just says this 

```
briefcase run

[helloworld] Starting app...


Unable to start app helloworld.
```
Please help, thanks

**Comment by freakboy3742** [comment]
Briefcase is currently unable to package mobile apps that contain binary dependencies. See beeware/briefcase#471 for details.
