### ISSUE TITLE
Tutorial Documentation Correction

### ISSUE THREAD

**Issue by Spider-ant** [beeware/beeware#83]
**Describe the bug**
https://docs.beeware.org/en/latest/tutorial/tutorial-4.html
Sub-title: Updating dependencies and icons
In the documentation (point 1) says ... 'will re-install your the application dependecies.'

**To Reproduce**
1. Go to https://docs.beeware.org/en/latest/tutorial/tutorial-4.html
2. Find sub-title 'Updating dependencies and icons
3. Find first point.
4. See bad english which says 'will re-install your the application dependecies.'

**Expected behavior**
Should say ... 'will re-install the application dependecies.'

**Screenshots**
<img width="706" alt="Screen Shot 2020-10-08 at 11 09 12 AM" src="https://user-images.githubusercontent.com/64494098/95477935-e47a7480-0956-11eb-9012-1b257e5b9ee5.png">

**Environment:**
n/a

**Additional context**
n/a

**Comment by Viridescence** [comment]
Fixed, issue can be closed.
