### ISSUE TITLE
how to use  `pycryptodome` in  ios project?

### ISSUE THREAD

**Issue by liyanhrxy** [beeware/beeware#86]
recently, I worked with the beeware tools to build a ios project, in python code i need the `pycryptodome`(a self-contained Python package of low-level cryptographic primitives) which contains some .so in it's package, however ,it doesn't work at all??  how can i do ??

**Comment by freakboy3742** [comment]
Unfortunately, this isn't currently possible - see beeware/briefcase#471 for details. It's something we *want* to fix, but we need time and resources to do so.
