### ISSUE TITLE
DetaildList not working on Ubuntu 

### ISSUE THREAD

**Issue by rickdps** [beeware/beeware#9]
Here is the code that doesn't work: 

self.chat = toga.DetailedList(data=[])

It gives me the following error: 

[GTK+] Not implemented: DetailedList.rehint()

Everything else is working perfectly so far.

Thank you for any help towards the solution.

**Comment by freakboy3742** [comment]
This isn't a problem with beeware; it's a limitation of the Toga toolkit. And, the the problem is exactly what the error says: The DetailedList widget hasn't been implemented yet. Toga is still in active development; not all widgets are available on all platforms.
