### ISSUE TITLE
Move section on possible installation errors from `Install the Beeware Tools` to `Bootstrap a new project`

### ISSUE THREAD

**Issue by obulat** [beeware/beeware#95]
**Is your feature request related to a problem? Please describe.**
Currently, pythonnet is not pip-installable with Python 3.9. There is a really good explanation of what can be done instead in the section called `Install the Beeware Tools`. However, this section relates to the `briefcase new` command, which installs briefcase-specific packages, and doesn't cause problems. The error arises during the next step, when you run `briefcase dev` and the pythonnet package is installed. 

**Describe the solution you'd like**
I think it would be clearer for beginners if we move the section on installation problems to the `Bootstrap a new project` section.

**Comment by freakboy3742** [comment]
👍 Agreed - the current location isn't the best option.
